#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CroutonLibrary.Resource", IsApplication=true)]

namespace CroutonLibrary
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f04004c
			public const int aliceBlue = 2130968652;
			
			// aapt resource value: 0x7f040042
			public const int antiqueWhite = 2130968642;
			
			// aapt resource value: 0x7f040098
			public const int aqua = 2130968728;
			
			// aapt resource value: 0x7f04007d
			public const int aquamarine = 2130968701;
			
			// aapt resource value: 0x7f04004a
			public const int azure = 2130968650;
			
			// aapt resource value: 0x7f040047
			public const int beige = 2130968647;
			
			// aapt resource value: 0x7f040030
			public const int bisque = 2130968624;
			
			// aapt resource value: 0x7f040023
			public const int black = 2130968611;
			
			// aapt resource value: 0x7f04002e
			public const int blanchedAlmond = 2130968622;
			
			// aapt resource value: 0x7f040022
			public const int blue = 2130968610;
			
			// aapt resource value: 0x7f040010
			public const int blueDark = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int blueLight = 2130968593;
			
			// aapt resource value: 0x7f040079
			public const int blueviolet = 2130968697;
			
			// aapt resource value: 0x7f04006d
			public const int brown = 2130968685;
			
			// aapt resource value: 0x7f040054
			public const int burlyWood = 2130968660;
			
			// aapt resource value: 0x7f040088
			public const int cadetBlue = 2130968712;
			
			// aapt resource value: 0x7f04007e
			public const int chartreuse = 2130968702;
			
			// aapt resource value: 0x7f04005e
			public const int chocolate = 2130968670;
			
			// aapt resource value: 0x7f040039
			public const int coral = 2130968633;
			
			// aapt resource value: 0x7f040087
			public const int cornflowerBlue = 2130968711;
			
			// aapt resource value: 0x7f04002a
			public const int cornsilk = 2130968618;
			
			// aapt resource value: 0x7f040057
			public const int crimson = 2130968663;
			
			// aapt resource value: 0x7f040018
			public const int customers_bar = 2130968600;
			
			// aapt resource value: 0x7f040099
			public const int cyan = 2130968729;
			
			// aapt resource value: 0x7f0400a1
			public const int darkBlue = 2130968737;
			
			// aapt resource value: 0x7f04009e
			public const int darkCyan = 2130968734;
			
			// aapt resource value: 0x7f040066
			public const int darkGoldenrod = 2130968678;
			
			// aapt resource value: 0x7f04009f
			public const int darkGreen = 2130968735;
			
			// aapt resource value: 0x7f040063
			public const int darkKhaki = 2130968675;
			
			// aapt resource value: 0x7f040077
			public const int darkMagenta = 2130968695;
			
			// aapt resource value: 0x7f040089
			public const int darkOliveGreen = 2130968713;
			
			// aapt resource value: 0x7f040038
			public const int darkOrange = 2130968632;
			
			// aapt resource value: 0x7f040070
			public const int darkOrchid = 2130968688;
			
			// aapt resource value: 0x7f040078
			public const int darkRed = 2130968696;
			
			// aapt resource value: 0x7f040051
			public const int darkSalmon = 2130968657;
			
			// aapt resource value: 0x7f040075
			public const int darkSeaGreen = 2130968693;
			
			// aapt resource value: 0x7f04008c
			public const int darkSlateBlue = 2130968716;
			
			// aapt resource value: 0x7f040092
			public const int darkSlateGray = 2130968722;
			
			// aapt resource value: 0x7f04009c
			public const int darkTurquoise = 2130968732;
			
			// aapt resource value: 0x7f040072
			public const int darkViolet = 2130968690;
			
			// aapt resource value: 0x7f04006c
			public const int darkgray = 2130968684;
			
			// aapt resource value: 0x7f04003d
			public const int deepPink = 2130968637;
			
			// aapt resource value: 0x7f04009d
			public const int deepSkyBlue = 2130968733;
			
			// aapt resource value: 0x7f040001
			public const int default_color = 2130968577;
			
			// aapt resource value: 0x7f040085
			public const int dimGray = 2130968709;
			
			// aapt resource value: 0x7f040096
			public const int dodgerBlue = 2130968726;
			
			// aapt resource value: 0x7f040067
			public const int fireBrick = 2130968679;
			
			// aapt resource value: 0x7f040028
			public const int floralWhite = 2130968616;
			
			// aapt resource value: 0x7f040094
			public const int forestGreen = 2130968724;
			
			// aapt resource value: 0x7f04001b
			public const int fuchsia = 2130968603;
			
			// aapt resource value: 0x7f040056
			public const int gainsboro = 2130968662;
			
			// aapt resource value: 0x7f040044
			public const int ghostWhite = 2130968644;
			
			// aapt resource value: 0x7f040034
			public const int gold = 2130968628;
			
			// aapt resource value: 0x7f040059
			public const int goldenrod = 2130968665;
			
			// aapt resource value: 0x7f0400a3
			public const int gray = 2130968739;
			
			// aapt resource value: 0x7f0400a4
			public const int gray2 = 2130968740;
			
			// aapt resource value: 0x7f04001c
			public const int gray_dark = 2130968604;
			
			// aapt resource value: 0x7f04001d
			public const int gray_medium = 2130968605;
			
			// aapt resource value: 0x7f040021
			public const int green = 2130968609;
			
			// aapt resource value: 0x7f04006b
			public const int greenYellow = 2130968683;
			
			// aapt resource value: 0x7f04000d
			public const int greendarkpale = 2130968589;
			
			// aapt resource value: 0x7f0400af
			public const int holo_blue_bright = 2130968751;
			
			// aapt resource value: 0x7f0400a9
			public const int holo_blue_dark = 2130968745;
			
			// aapt resource value: 0x7f0400a5
			public const int holo_blue_light = 2130968741;
			
			// aapt resource value: 0x7f0400b0
			public const int holo_gray_bright = 2130968752;
			
			// aapt resource value: 0x7f0400a6
			public const int holo_gray_light = 2130968742;
			
			// aapt resource value: 0x7f0400aa
			public const int holo_green_dark = 2130968746;
			
			// aapt resource value: 0x7f0400a7
			public const int holo_green_light = 2130968743;
			
			// aapt resource value: 0x7f0400ae
			public const int holo_orange_dark = 2130968750;
			
			// aapt resource value: 0x7f0400ad
			public const int holo_orange_light = 2130968749;
			
			// aapt resource value: 0x7f0400ac
			public const int holo_purple = 2130968748;
			
			// aapt resource value: 0x7f0400ab
			public const int holo_red_dark = 2130968747;
			
			// aapt resource value: 0x7f0400a8
			public const int holo_red_light = 2130968744;
			
			// aapt resource value: 0x7f04004b
			public const int honeydew = 2130968651;
			
			// aapt resource value: 0x7f04003a
			public const int hotPink = 2130968634;
			
			// aapt resource value: 0x7f040060
			public const int indianRed = 2130968672;
			
			// aapt resource value: 0x7f04008a
			public const int indigo = 2130968714;
			
			// aapt resource value: 0x7f040019
			public const int interpreters_bar = 2130968601;
			
			// aapt resource value: 0x7f040024
			public const int ivory = 2130968612;
			
			// aapt resource value: 0x7f04004d
			public const int khaki = 2130968653;
			
			// aapt resource value: 0x7f040052
			public const int lavender = 2130968658;
			
			// aapt resource value: 0x7f04002c
			public const int lavenderBlush = 2130968620;
			
			// aapt resource value: 0x7f04007f
			public const int lawnGreen = 2130968703;
			
			// aapt resource value: 0x7f040029
			public const int lemonChiffon = 2130968617;
			
			// aapt resource value: 0x7f040015
			public const int lightBlue = 2130968597;
			
			// aapt resource value: 0x7f04004e
			public const int lightCoral = 2130968654;
			
			// aapt resource value: 0x7f040053
			public const int lightCyan = 2130968659;
			
			// aapt resource value: 0x7f040040
			public const int lightGoldenrodYellow = 2130968640;
			
			// aapt resource value: 0x7f040074
			public const int lightGreen = 2130968692;
			
			// aapt resource value: 0x7f04005c
			public const int lightGrey = 2130968668;
			
			// aapt resource value: 0x7f040036
			public const int lightPink = 2130968630;
			
			// aapt resource value: 0x7f040037
			public const int lightSalmon = 2130968631;
			
			// aapt resource value: 0x7f040095
			public const int lightSeaGreen = 2130968725;
			
			// aapt resource value: 0x7f04007a
			public const int lightSkyBlue = 2130968698;
			
			// aapt resource value: 0x7f040081
			public const int lightSlateGray = 2130968705;
			
			// aapt resource value: 0x7f040069
			public const int lightSteelBlue = 2130968681;
			
			// aapt resource value: 0x7f040025
			public const int lightYellow = 2130968613;
			
			// aapt resource value: 0x7f04001f
			public const int lime = 2130968607;
			
			// aapt resource value: 0x7f040091
			public const int limeGreen = 2130968721;
			
			// aapt resource value: 0x7f040041
			public const int linen = 2130968641;
			
			// aapt resource value: 0x7f04000c
			public const int linkColor = 2130968588;
			
			// aapt resource value: 0x7f04003e
			public const int magenta = 2130968638;
			
			// aapt resource value: 0x7f04001e
			public const int maroon = 2130968606;
			
			// aapt resource value: 0x7f040086
			public const int mediumAquamarine = 2130968710;
			
			// aapt resource value: 0x7f0400a0
			public const int mediumBlue = 2130968736;
			
			// aapt resource value: 0x7f040065
			public const int mediumOrchid = 2130968677;
			
			// aapt resource value: 0x7f040073
			public const int mediumPurple = 2130968691;
			
			// aapt resource value: 0x7f040090
			public const int mediumSeaGreen = 2130968720;
			
			// aapt resource value: 0x7f040080
			public const int mediumSlateBlue = 2130968704;
			
			// aapt resource value: 0x7f04009b
			public const int mediumSpringGreen = 2130968731;
			
			// aapt resource value: 0x7f04008b
			public const int mediumTurquoise = 2130968715;
			
			// aapt resource value: 0x7f040061
			public const int mediumVioletRed = 2130968673;
			
			// aapt resource value: 0x7f04000b
			public const int menuItemSelected = 2130968587;
			
			// aapt resource value: 0x7f04000a
			public const int menuItemUnselected = 2130968586;
			
			// aapt resource value: 0x7f040016
			public const int menuTextColor = 2130968598;
			
			// aapt resource value: 0x7f040097
			public const int midnightBlue = 2130968727;
			
			// aapt resource value: 0x7f040045
			public const int mintCream = 2130968645;
			
			// aapt resource value: 0x7f04002f
			public const int mistyRose = 2130968623;
			
			// aapt resource value: 0x7f040031
			public const int moccasin = 2130968625;
			
			// aapt resource value: 0x7f040032
			public const int navajoWhite = 2130968626;
			
			// aapt resource value: 0x7f0400a2
			public const int navy = 2130968738;
			
			// aapt resource value: 0x7f04003f
			public const int oldLace = 2130968639;
			
			// aapt resource value: 0x7f04007c
			public const int olive = 2130968700;
			
			// aapt resource value: 0x7f040083
			public const int oliveDrab = 2130968707;
			
			// aapt resource value: 0x7f040012
			public const int orange = 2130968594;
			
			// aapt resource value: 0x7f04003c
			public const int orangeRed = 2130968636;
			
			// aapt resource value: 0x7f04005a
			public const int orchid = 2130968666;
			
			// aapt resource value: 0x7f04004f
			public const int paleGoldenrod = 2130968655;
			
			// aapt resource value: 0x7f040071
			public const int paleGreen = 2130968689;
			
			// aapt resource value: 0x7f04006a
			public const int paleTurquoise = 2130968682;
			
			// aapt resource value: 0x7f040058
			public const int paleVioletRed = 2130968664;
			
			// aapt resource value: 0x7f04002d
			public const int papayaWhip = 2130968621;
			
			// aapt resource value: 0x7f04000f
			public const int peach = 2130968591;
			
			// aapt resource value: 0x7f040033
			public const int peachPuff = 2130968627;
			
			// aapt resource value: 0x7f04005f
			public const int peru = 2130968671;
			
			// aapt resource value: 0x7f040035
			public const int pink = 2130968629;
			
			// aapt resource value: 0x7f040055
			public const int plum = 2130968661;
			
			// aapt resource value: 0x7f040068
			public const int powderBlue = 2130968680;
			
			// aapt resource value: 0x7f040000
			public const int pressed_color = 2130968576;
			
			// aapt resource value: 0x7f040017
			public const int purple = 2130968599;
			
			// aapt resource value: 0x7f04000e
			public const int purpleish = 2130968590;
			
			// aapt resource value: 0x7f040013
			public const int red = 2130968595;
			
			// aapt resource value: 0x7f040014
			public const int redLight = 2130968596;
			
			// aapt resource value: 0x7f040064
			public const int rosyBrown = 2130968676;
			
			// aapt resource value: 0x7f04008e
			public const int royalBlue = 2130968718;
			
			// aapt resource value: 0x7f040076
			public const int saddleBrown = 2130968694;
			
			// aapt resource value: 0x7f040043
			public const int salmon = 2130968643;
			
			// aapt resource value: 0x7f040049
			public const int sandyBrown = 2130968649;
			
			// aapt resource value: 0x7f040093
			public const int seaGreen = 2130968723;
			
			// aapt resource value: 0x7f04002b
			public const int seashell = 2130968619;
			
			// aapt resource value: 0x7f04006e
			public const int sienna = 2130968686;
			
			// aapt resource value: 0x7f040062
			public const int silver = 2130968674;
			
			// aapt resource value: 0x7f04007b
			public const int skyBlue = 2130968699;
			
			// aapt resource value: 0x7f040084
			public const int slateBlue = 2130968708;
			
			// aapt resource value: 0x7f040082
			public const int slateGray = 2130968706;
			
			// aapt resource value: 0x7f040027
			public const int snow = 2130968615;
			
			// aapt resource value: 0x7f04009a
			public const int springGreen = 2130968730;
			
			// aapt resource value: 0x7f04008d
			public const int steelBlue = 2130968717;
			
			// aapt resource value: 0x7f04005d
			public const int tan = 2130968669;
			
			// aapt resource value: 0x7f040020
			public const int teal = 2130968608;
			
			// aapt resource value: 0x7f04005b
			public const int thistle = 2130968667;
			
			// aapt resource value: 0x7f04003b
			public const int tomato = 2130968635;
			
			// aapt resource value: 0x7f04008f
			public const int turquoise = 2130968719;
			
			// aapt resource value: 0x7f040050
			public const int violet = 2130968656;
			
			// aapt resource value: 0x7f040002
			public const int vpi__background_holo_dark = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int vpi__background_holo_light = 2130968579;
			
			// aapt resource value: 0x7f040006
			public const int vpi__bright_foreground_disabled_holo_dark = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int vpi__bright_foreground_disabled_holo_light = 2130968583;
			
			// aapt resource value: 0x7f040004
			public const int vpi__bright_foreground_holo_dark = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int vpi__bright_foreground_holo_light = 2130968581;
			
			// aapt resource value: 0x7f040008
			public const int vpi__bright_foreground_inverse_holo_dark = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int vpi__bright_foreground_inverse_holo_light = 2130968585;
			
			// aapt resource value: 0x7f040048
			public const int wheat = 2130968648;
			
			// aapt resource value: 0x7f04001a
			public const int white = 2130968602;
			
			// aapt resource value: 0x7f040046
			public const int whiteSmoke = 2130968646;
			
			// aapt resource value: 0x7f040026
			public const int yellow = 2130968614;
			
			// aapt resource value: 0x7f04006f
			public const int yellowGreen = 2130968687;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int monoandroidsplash = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070000
			public const int MyButton = 2131165184;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Mono_Android_Theme_Splash = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
